"""Auto-generated by sage/dynamic_api/generate.py.

Benchmark: sage_bench
Tools: 5
Generated: 2026-06-19 04:33:16

Drop this file into sage/src/functions/tools/synthesized.py to activate.
"""
from typing import List, Dict, Any
from sage.src.functions.tools.search import unified_web_search, parse_web_data
from sage.src.functions.tools.extract import extract_parts_from_timestamp
from sage.src.functions.tools.reason import perform_reasoning
from sage.src.functions.tools.temporal import identify_timestamps_visually
from sage.src.functions.tools.audio import verbal_transcript


def _extract_visual_and_verbal_details(video_path: str, timestamp_start: str, timestamp_end: str) -> dict:
    """Extract visual and verbal details from a specific time window in a video. Useful for gathering evidence on visual appearances and spoken content within a defined period.

    Args:
        video_path: Path to the video.
        timestamp_start: Start of the time window in HH:MM:SS.
        timestamp_end: End of the time window in HH:MM:SS.

    Returns:
        Dict with "frames_analyzed" (list of frame paths) and "transcript" (str).
    """
    extracted = extract_parts_from_timestamp(
        video_path=video_path,
        timestamp_start=timestamp_start,
        timestamp_end=timestamp_end,
        extract_type="frames",
    )
    frames = extracted.get("media_paths", [])
    transcript_data = verbal_transcript(
        video_path=video_path,
        timestamp_start=timestamp_start,
        timestamp_end=timestamp_end,
    )
    transcript = transcript_data.get("transcript", "")
    return {
        "frames_analyzed": frames,
        "transcript": transcript,
    }


def _reason_over_visual_details(video_path: str, timestamp_start: str, timestamp_end: str, query: str) -> dict:
    """Perform reasoning on visual details extracted from a video segment. Useful for reasoning over specific visual content such as outfits, objects, or appearances.

    Args:
        video_path: Path to the video.
        timestamp_start: Start of the time window in HH:MM:SS.
        timestamp_end: End of the time window in HH:MM:SS.
        query: Specific visual details to be reasoned about.

    Returns:
        Dict with "candidate_answer" (str) and "details" (dict of visual observations and context).
    """
    extracted = extract_parts_from_timestamp(
        video_path=video_path,
        timestamp_start=timestamp_start,
        timestamp_end=timestamp_end,
        extract_type="frames",
    )
    frames = extracted.get("media_paths", [])
    if not frames:
        return {"candidate_answer": "", "details": {"observations": "", "frames_analyzed": 0, "window": {"start": timestamp_start, "end": timestamp_end}, "error": "no frames extracted"}}
    result = perform_reasoning(
        query=f"Report concrete, verifiable visual details about {query} across these frames: EXACT colors, counts, any on-screen text or numbers, and specific names. List what is visible. Do NOT answer any question and do NOT give a single summary verdict — report only the raw observations.",
        media_paths=frames,
        mode="observe",
    )
    return {
        "candidate_answer": "",
        "details": {
            "observations": result.get("observations", ""),
            "frames_analyzed": len(frames),
            "media_paths": frames,
            "window": {"start": timestamp_start, "end": timestamp_end},
        },
    }


def _aggregate_evidence_for_multiple_choice(video_path: str, timestamp_start: str, timestamp_end: str, options: list) -> dict:
    """Aggregate visual and verbal evidence for multiple-choice questions from a video. Useful for comparing visual evidence to multiple-choice options.

    Args:
        video_path: Path to the video.
        timestamp_start: Start of the time window in HH:MM:SS.
        timestamp_end: End of the time window in HH:MM:SS.
        options: List of multiple-choice options.

    Returns:
        Dict with "frames_analyzed" (list of frame paths), "transcript" (str), and "candidate_match" (str) suggesting the most likely option.
    """
    extracted = extract_parts_from_timestamp(
        video_path=video_path,
        timestamp_start=timestamp_start,
        timestamp_end=timestamp_end,
        extract_type="frames",
    )
    frames = extracted.get("media_paths", [])
    transcript_data = verbal_transcript(
        video_path=video_path,
        timestamp_start=timestamp_start,
        timestamp_end=timestamp_end,
    )
    transcript = transcript_data.get("transcript", "")
    if not frames:
        return {
            "frames_analyzed": [],
            "transcript": transcript,
            "candidate_match": "",
            "error": "no frames extracted"
        }
    result = perform_reasoning(
        query=f"Transcript of this segment: {transcript}\n\nUsing the transcript and these frames, compare the visual and verbal evidence to the following options: {options}. Report the most likely option based on exact wording, visible text, colors, and counts. Do NOT answer any question and do NOT produce a summary verdict — list only the raw observations and exact quotes.",
        media_paths=frames,
        mode="observe",
    )
    return {
        "frames_analyzed": frames,
        "transcript": transcript,
        "candidate_match": result.get("observations", ""),
    }


def _transcribe_topic_related_speech(video_path: str, topic_description: str, timestamp_start: str, timestamp_end: str) -> dict:
    """Identify and transcribe speech related to a specific topic within a video segment.

    Args:
        video_path: Path to the video.
        topic_description: Description of the speech topic.
        timestamp_start: HH:MM:SS — start of the transcription window.
        timestamp_end: HH:MM:SS — end of the transcription window.

    Returns:
        Dict with "transcript" of the identified speech and "timestamps" marking the start and end of relevant speech sections.
    """
    identified = identify_timestamps_visually(
        video_path=video_path,
        event=topic_description,
        timestamp_start=timestamp_start,
        timestamp_end=timestamp_end,
    )
    if not isinstance(identified, dict):
        return {"transcript": "", "timestamps": {}, "error": "timestamp identification returned no structured result"}

    timestamps = identified.get("timestamps", {})
    if not timestamps or timestamps.get("start") is None or timestamps.get("end") is None:
        return {"transcript": "", "timestamps": {}, "error": "relevant speech timestamps not identified"}

    transcript_data = verbal_transcript(
        video_path=video_path,
        timestamp_start=timestamps.get("start"),
        timestamp_end=timestamps.get("end"),
    )
    transcript = transcript_data.get("transcript", "")

    return {
        "transcript": transcript,
        "timestamps": timestamps,
    }


def _identify_and_describe_event(video_path: str, event_description: str, timestamp_start: str, timestamp_end: str) -> dict:
    """Analyze a video segment to identify and describe actions or events fitting a particular description.

    Args:
        video_path: Path to the video.
        event_description: Description of the event/action to identify.
        timestamp_start: HH:MM:SS — start of the event search window.
        timestamp_end: HH:MM:SS — end of the event search window.

    Returns:
        Dict with "observations" detailing the identified event/action and "timestamps" marking its occurrence.
    """
    identified = identify_timestamps_visually(
        video_path=video_path,
        event=event_description,
        timestamp_start=timestamp_start,
        timestamp_end=timestamp_end,
    )
    if not isinstance(identified, dict):
        return {"observations": "", "timestamps": {}, "error": "timestamp identification returned no structured result"}

    timestamps = identified.get("timestamps", {})
    if not timestamps or timestamps.get("start") is None or timestamps.get("end") is None:
        return {"observations": "", "timestamps": {}, "error": "event timestamps not identified"}

    extracted = extract_parts_from_timestamp(
        video_path=video_path,
        timestamp_start=timestamps["start"],
        timestamp_end=timestamps["end"],
        extract_type="frames",
    )
    frames = extracted.get("media_paths", [])
    if not frames:
        return {"observations": "", "timestamps": timestamps, "error": "no frames extracted"}

    result = perform_reasoning(
        query=f"Identify and describe the event or action fitting the description '{event_description}'. Report exact actions, visible text, colors, and specific names. Do NOT answer any question and do NOT produce a summary verdict — list only the raw observations.",
        media_paths=frames,
        mode="observe",
    )

    return {
        "observations": result.get("observations", ""),
        "timestamps": timestamps,
        "frames_analyzed": len(frames),
        "media_paths": frames,
    }
